### ISSUE TITLE
Force Close/Stopped fix in android 6.0+

### ISSUE THREAD

**Issue by NinjaGaurav** [NinjaGaurav/DirectDialer#1]
If you are using Android 6.0 (Marshmallow) or above you need to manually open the app info from Android Settings and grant the permissions for the app to run properly else you will receive Force Close/Stopped working messages. This will be fixed when Auto Request Permission on Startup is implemented.

**Comment by Nagendra1421** [comment]
Can I work on this issue?

**Comment by NinjaGaurav** [comment]
> Can I work on this issue?

Yes

**Comment by yashagldit** [comment]
I fixed all the errors how to push it?
I cant create pull request.. it says 403 you are not allowed

**Comment by sankalpchauhan-me** [comment]
PR #7

**Comment by sankalpchauhan-me** [comment]
Please take a look at my comment under #9 and at PR #10

**Comment by NinjaGaurav** [comment]
> Please take a look at my comment under #9 and at PR #10 ( I have fixed this issue and attached a video to show working of the app after the issue is fixed under comment section of PR #10 ). Do let me know if you encounter any further issue in my PR.

Thanks, I updated readme and merged the PR.
