### ISSUE TITLE
Add screenshots of app in readme

### ISSUE THREAD

**Issue by NinjaGaurav** [NinjaGaurav/DirectDialer#2]
Add screenshots of app in readme

**Comment by CoderJolly** [comment]
assign it me, i willl do it

**Comment by NinjaGaurav** [comment]
ok

**Comment by CoderJolly** [comment]
this first issue keeps popping up though i have given all permissions as stated in issue 1

**Comment by NinjaGaurav** [comment]
it worked for me please check if u granted all permissions again
