### ISSUE TITLE
build.gradle has older dependencies and still uses 'compile' configuration

### ISSUE THREAD

**Issue by sud8443** [NinjaGaurav/DirectDialer#4]
The build.gradle in the multi-project build has older dependencies which are causing problems in build and those files still use 'compile' configuration which is obsolete and has been replaced by 'implementation'

**Comment by yashagldit** [comment]
I fixed all the errors how to push it?

**Comment by sud8443** [comment]
@yashagldit I have already fixed the errors and hence raised the issue for the same.
